name       : qt5-networkauth
version    : 5.13.0
release    : 5
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.0/submodules/qtnetworkauth-everywhere-src-5.13.0.tar.xz : 91ff879d0a9f7e8ff658fb569136f102ee9f25bd47852e97a1f39826c1932c0d
license    :
    - GFDL-1.3-only
    - GPL-3.0-only
component  : desktop.qt
summary    : Qt5 NetworkAuth components
description: |
    Qt5 NetworkAuth components
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %qmake CONFIG+=release
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
