name       : qt5-networkauth
version    : 5.13.1
release    : 6
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.1/submodules/qtnetworkauth-everywhere-src-5.13.1.tar.xz : d5306dd7d6aa128382505046b06ad7f9c17c56a9c4277dc862c13add06b89e4a
license    :
    - GFDL-1.3-only
    - GPL-3.0-only
component  : desktop.qt
summary    : Qt5 NetworkAuth components
description: |
    Qt5 NetworkAuth components
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %qmake CONFIG+=release
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
