name       : qt5-networkauth
version    : 5.15.1
release    : 9
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.1/submodules/qtnetworkauth-everywhere-src-5.15.1.tar.xz : e5e37ae8f842e4bb66f1e719d8585ef71bc13c79545054fcd26072cd58e4d4c2
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-only
    - GPL-3.0-only
component  : desktop.qt
summary    : Qt5 NetworkAuth components
description: |
    Qt5 NetworkAuth components
builddeps  :
    - pkgconfig(Qt5Core)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtnetworkauth.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
