name       : qt5-networkauth
version    : 5.15.8
release    : 18
source     :
    - git|https://invent.kde.org/qt/qt/qtnetworkauth.git : f082a4c84c54e888b8d023ba68b7085551403425
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-only
    - GPL-3.0-only
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 NetworkAuth components
description: |
    Qt5 NetworkAuth components
builddeps  :
    - pkgconfig(Qt5Core)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtnetworkauth.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
