name       : qt5-networkauth
version    : 5.12.1
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtnetworkauth-everywhere-src-5.12.1.tar.xz : 090fbb6be35b2f2edf7cc4cb32f0f9c27a9a66defa06f6d23e1397836e31d44c
license    :
    - GFDL-1.3-only
    - GPL-3.0-only
component  : desktop.qt
summary    : Qt5 NetworkAuth components
description: |
    Qt5 NetworkAuth components
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %qmake CONFIG+=release
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
