name       : qt5-networkauth
version    : 5.15.3
release    : 13
source     :
    - git|https://invent.kde.org/qt/qt/qtnetworkauth.git : 53870ee9bb9117702cd1f11cb1c5d1cfc2d5394a
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-only
    - GPL-3.0-only
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 NetworkAuth components
description: |
    Qt5 NetworkAuth components
builddeps  :
    - pkgconfig(Qt5Core)
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtnetworkauth.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
