name       : qt5-networkauth
version    : 5.12.2
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.2/submodules/qtnetworkauth-everywhere-src-5.12.2.tar.xz : 5876c1d8e37238eca8d5fbc945dfeb90bac013597bcac5c5beff23c12a8a4383
license    :
    - GFDL-1.3-only
    - GPL-3.0-only
component  : desktop.qt
summary    : Qt5 NetworkAuth components
description: |
    Qt5 NetworkAuth components
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %qmake CONFIG+=release
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
