name       : qt5-networkauth
version    : 5.12.3
release    : 4
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qtnetworkauth-everywhere-src-5.12.3.tar.xz : dd6bf334be29fb82adaeecb184779328b4ad33a069528b9954d9c07f2d889332
license    :
    - GFDL-1.3-only
    - GPL-3.0-only
component  : desktop.qt
summary    : Qt5 NetworkAuth components
description: |
    Qt5 NetworkAuth components
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %qmake CONFIG+=release
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
