name       : qt5-networkauth
version    : 5.11.2
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/5.11/5.11.2/submodules/qtnetworkauth-everywhere-src-5.11.2.tar.xz : 79379cef7801fb909ed1cd23379eaef6b2d2ca31581aa537cab64ee1e0dcb7fe
license    :
    - GFDL-1.3-only
    - GPL-3.0-only
component  : desktop.qt
summary    : Qt5 NetworkAuth components
description: |
    Qt5 NetworkAuth components
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %qmake CONFIG+=release
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
